### ISSUE TITLE
IpadMini4 10.3.1 battery drain by "backboardd"

### ISSUE THREAD

**Issue by parazyt75** [tihmstar/doubleH3lix#13]
Hi all,
I recently switched from g0blin RC2 to DoubleH3lix RC6 on my ipadmini 4 ios 10.3.1
I noticed that “backboardd” always uses between 6 and 10% of CPU usage.
I think the cause of the battery depletion.
I have nothing more Cydia, BatteryLife, Cydia Erazer, DetailledBatteryUsage, Ext3nderInstaller, MTerminal and Top installed.
I do not use my device to be sure that it is not me who discharges the battery.
After 3 days, I lost 80% of the battery
Did any of us notice the same behavior?
Did anyone of us noticed that too ?

**Comment by ghost** [comment]
Backboardd is a deamon to help the springboard. Its normal

**Comment by parazyt75** [comment]
I think I’ve found which tweak drain my battery. 
It's Ext3nder Installer.
Even if I set ext3nder to check every 12 hours & 1 day resign when missing.
I have to disable it with Icleaner Pro.
Good news for the battery life.
Bad news for auto resign DoubleH3lix.

I will like a tweak like "Iconcert" for DoubleH3lix.
...
