### ISSUE TITLE
How to build doubleH3lix?

### ISSUE THREAD

**Issue by pappanunny** [tihmstar/doubleH3lix#21]
I am trying to build doubleH3lix on xcode 11.3 on macOS catalina, but is getting the error "Xcode showing "liboffsetfinder64/liboffsetfinder64.hpp' file not found error". 

I have already installed liboffsetfinder64 as shown below:

ls -la /usr/local/lib | grep offsetfinder
-rwxr-xr-x    1 user  admin   171784 Feb 10 10:52 liboffsetfinder64.0.dylib
-rw-r--r--    1 user  admin  2065872 Feb 10 10:52 liboffsetfinder64.a
lrwxr-xr-x    1 user  admin       25 Feb 10 10:52 liboffsetfinder64.dylib -> liboffsetfinder64.0.dylib

I also tried changing the header search paths to add /usr/local/lib to the current setting.

What am I missing here? How can i build it successfully?
@Siguza @tihmstar 

Thanks in advance..

**Comment by Siguza** [comment]
`git submodule update --init --recursive`

**Comment by pappanunny** [comment]
Yes! It worked now!!.. Thank you @Siguza. Much appreciated!!

**Comment by pappanunny** [comment]
For those looking for the way to build...

Use recursive clone of the git repo.  

```git clone --recursive [URL to doubleH3lix Git repo]```

**_If you missed the recursive parameter_**, then use the command Siguza mentioned above. 

```git submodule update --init --recursive```

Now open the doubleH3lix Xcode project and build it and it should work.

Thanks!

**Comment by frakman1** [comment]
Would it kill you to put this step in a README.md file?
