### ISSUE TITLE
G0blin to ‫doubleH3lix‬

### ISSUE THREAD

**Issue by itsyasso** [tihmstar/doubleH3lix#4]
I already jailbreaking by g0blin RC2. I wanna to change to ‫doubleH3lix‬. 
What should i do? Reboot or use Eraser.

**Comment by ghost** [comment]
Just sideload ipa in nonjailed state and run it

**Comment by itsyasso** [comment]
You're right viddy135.
Just reboot and run doubleH3lix 👌🏼
